sonata_admin:
    title: 'Maajabu Rafiki'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    
    title_logo: images/logo_title.png 

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
